[package]
name = "qwen-asr-cli"
version = "0.8.2"
edition.workspace = true
license.workspace = true
description = "CLI for qwen-asr: Qwen3-ASR speech-to-text"
keywords = ["asr", "speech-recognition", "qwen", "cli"]
categories = ["command-line-utilities", "multimedia::audio"]
repository = "https://github.com/huanglizhuo/QwenASR"
homepage = "https://github.com/huanglizhuo/QwenASR"
readme = "README.md"

[[bin]]
name = "qwen-asr"
path = "src/main.rs"

[features]
default = ["qwen-asr/blas", "qwen-asr/vdsp"]
int8-prefill = ["qwen-asr/int8-prefill"]
int8-encoder = ["qwen-asr/int8-encoder"]

[dependencies]
qwen-asr = { version = "0.9.0", path = "../qwen-asr", default-features = false }
ureq = "2"
ctrlc = "3"

[target.'cfg(target_os = "macos")'.dependencies]
coreaudio-sys = "0.2"
