// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QasrEngine>>
abstract class QasrEngine implements RustOpaqueInterface {
  /// Load model from a directory path. Returns None if loading fails.
  static Future<QasrEngine?> load({
    required String modelDir,
    required int nThreads,
    required int verbosity,
  }) => RustLib.instance.api.crateApiQasrBridgeQasrEngineLoad(
    modelDir: modelDir,
    nThreads: nThreads,
    verbosity: verbosity,
  );

  /// Get last transcription performance stats as a formatted string.
  String perfStats();

  /// Set the forced language. Returns false if the language is invalid.
  bool setLanguage({required String language});

  /// Set the segment duration in seconds (0 = no segmentation).
  void setSegmentSec({required double sec});

  /// Transcribe a WAV file at the given path.
  Future<String?> transcribeFile({required String wavPath});

  /// Transcribe raw PCM f32 samples (16kHz mono).
  Future<String?> transcribePcm({required List<double> samples});

  /// Transcribe from a WAV file buffer (bytes).
  Future<String?> transcribeWavBuffer({required List<int> wavData});
}
