// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/qwen_asr_bridge.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiQwenAsrBridgeInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 489568414;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_qwen_asr',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<QwenAsrEngine?> crateApiQwenAsrBridgeQwenAsrEngineLoad({
    required String modelDir,
    required int nThreads,
    required int verbosity,
  });

  String crateApiQwenAsrBridgeQwenAsrEnginePerfStats({
    required QwenAsrEngine that,
  });

  bool crateApiQwenAsrBridgeQwenAsrEngineSetLanguage({
    required QwenAsrEngine that,
    required String language,
  });

  void crateApiQwenAsrBridgeQwenAsrEngineSetMultilingual({
    required QwenAsrEngine that,
    required bool enabled,
  });

  void crateApiQwenAsrBridgeQwenAsrEngineSetPastTextConditioning({
    required QwenAsrEngine that,
    required bool enabled,
  });

  void crateApiQwenAsrBridgeQwenAsrEngineSetSegmentSec({
    required QwenAsrEngine that,
    required double sec,
  });

  void crateApiQwenAsrBridgeQwenAsrEngineSetStreamChunkSec({
    required QwenAsrEngine that,
    required double sec,
  });

  void crateApiQwenAsrBridgeQwenAsrEngineSetStreamMaxNewTokens({
    required QwenAsrEngine that,
    required int tokens,
  });

  void crateApiQwenAsrBridgeQwenAsrEngineSetStreamRollback({
    required QwenAsrEngine that,
    required int tokens,
  });

  void crateApiQwenAsrBridgeQwenAsrEngineSetStreamUnfixedChunks({
    required QwenAsrEngine that,
    required int chunks,
  });

  void crateApiQwenAsrBridgeQwenAsrEngineSetVadSegmentReset({
    required QwenAsrEngine that,
    required bool enabled,
  });

  Future<StreamPartial> crateApiQwenAsrBridgeQwenAsrEngineStreamPush({
    required QwenAsrEngine that,
    required List<double> samples,
    required bool finalize,
  });

  Future<void> crateApiQwenAsrBridgeQwenAsrEngineStreamReset({
    required QwenAsrEngine that,
  });

  Future<String?> crateApiQwenAsrBridgeQwenAsrEngineTranscribeFile({
    required QwenAsrEngine that,
    required String wavPath,
  });

  Future<String?> crateApiQwenAsrBridgeQwenAsrEngineTranscribePcm({
    required QwenAsrEngine that,
    required List<double> samples,
  });

  Future<String?> crateApiQwenAsrBridgeQwenAsrEngineTranscribeWavBuffer({
    required QwenAsrEngine that,
    required List<int> wavData,
  });

  Future<void> crateApiQwenAsrBridgeInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_QwenAsrEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_QwenAsrEngine;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QwenAsrEnginePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<QwenAsrEngine?> crateApiQwenAsrBridgeQwenAsrEngineLoad({
    required String modelDir,
    required int nThreads,
    required int verbosity,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelDir, serializer);
          sse_encode_i_32(nThreads, serializer);
          sse_encode_i_32(verbosity, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQwenAsrBridgeQwenAsrEngineLoadConstMeta,
        argValues: [modelDir, nThreads, verbosity],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQwenAsrBridgeQwenAsrEngineLoadConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_load",
        argNames: ["modelDir", "nThreads", "verbosity"],
      );

  @override
  String crateApiQwenAsrBridgeQwenAsrEnginePerfStats({
    required QwenAsrEngine that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQwenAsrBridgeQwenAsrEnginePerfStatsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQwenAsrBridgeQwenAsrEnginePerfStatsConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_perf_stats",
        argNames: ["that"],
      );

  @override
  bool crateApiQwenAsrBridgeQwenAsrEngineSetLanguage({
    required QwenAsrEngine that,
    required String language,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          sse_encode_String(language, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQwenAsrBridgeQwenAsrEngineSetLanguageConstMeta,
        argValues: [that, language],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQwenAsrBridgeQwenAsrEngineSetLanguageConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_set_language",
        argNames: ["that", "language"],
      );

  @override
  void crateApiQwenAsrBridgeQwenAsrEngineSetMultilingual({
    required QwenAsrEngine that,
    required bool enabled,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          sse_encode_bool(enabled, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQwenAsrBridgeQwenAsrEngineSetMultilingualConstMeta,
        argValues: [that, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiQwenAsrBridgeQwenAsrEngineSetMultilingualConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_set_multilingual",
        argNames: ["that", "enabled"],
      );

  @override
  void crateApiQwenAsrBridgeQwenAsrEngineSetPastTextConditioning({
    required QwenAsrEngine that,
    required bool enabled,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          sse_encode_bool(enabled, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiQwenAsrBridgeQwenAsrEngineSetPastTextConditioningConstMeta,
        argValues: [that, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiQwenAsrBridgeQwenAsrEngineSetPastTextConditioningConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_set_past_text_conditioning",
        argNames: ["that", "enabled"],
      );

  @override
  void crateApiQwenAsrBridgeQwenAsrEngineSetSegmentSec({
    required QwenAsrEngine that,
    required double sec,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          sse_encode_f_32(sec, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQwenAsrBridgeQwenAsrEngineSetSegmentSecConstMeta,
        argValues: [that, sec],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQwenAsrBridgeQwenAsrEngineSetSegmentSecConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_set_segment_sec",
        argNames: ["that", "sec"],
      );

  @override
  void crateApiQwenAsrBridgeQwenAsrEngineSetStreamChunkSec({
    required QwenAsrEngine that,
    required double sec,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          sse_encode_f_32(sec, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiQwenAsrBridgeQwenAsrEngineSetStreamChunkSecConstMeta,
        argValues: [that, sec],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiQwenAsrBridgeQwenAsrEngineSetStreamChunkSecConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_set_stream_chunk_sec",
        argNames: ["that", "sec"],
      );

  @override
  void crateApiQwenAsrBridgeQwenAsrEngineSetStreamMaxNewTokens({
    required QwenAsrEngine that,
    required int tokens,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          sse_encode_i_32(tokens, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiQwenAsrBridgeQwenAsrEngineSetStreamMaxNewTokensConstMeta,
        argValues: [that, tokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiQwenAsrBridgeQwenAsrEngineSetStreamMaxNewTokensConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_set_stream_max_new_tokens",
        argNames: ["that", "tokens"],
      );

  @override
  void crateApiQwenAsrBridgeQwenAsrEngineSetStreamRollback({
    required QwenAsrEngine that,
    required int tokens,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          sse_encode_i_32(tokens, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiQwenAsrBridgeQwenAsrEngineSetStreamRollbackConstMeta,
        argValues: [that, tokens],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiQwenAsrBridgeQwenAsrEngineSetStreamRollbackConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_set_stream_rollback",
        argNames: ["that", "tokens"],
      );

  @override
  void crateApiQwenAsrBridgeQwenAsrEngineSetStreamUnfixedChunks({
    required QwenAsrEngine that,
    required int chunks,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          sse_encode_i_32(chunks, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiQwenAsrBridgeQwenAsrEngineSetStreamUnfixedChunksConstMeta,
        argValues: [that, chunks],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiQwenAsrBridgeQwenAsrEngineSetStreamUnfixedChunksConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_set_stream_unfixed_chunks",
        argNames: ["that", "chunks"],
      );

  @override
  void crateApiQwenAsrBridgeQwenAsrEngineSetVadSegmentReset({
    required QwenAsrEngine that,
    required bool enabled,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          sse_encode_bool(enabled, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiQwenAsrBridgeQwenAsrEngineSetVadSegmentResetConstMeta,
        argValues: [that, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiQwenAsrBridgeQwenAsrEngineSetVadSegmentResetConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_set_vad_segment_reset",
        argNames: ["that", "enabled"],
      );

  @override
  Future<StreamPartial> crateApiQwenAsrBridgeQwenAsrEngineStreamPush({
    required QwenAsrEngine that,
    required List<double> samples,
    required bool finalize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          sse_encode_list_prim_f_32_loose(samples, serializer);
          sse_encode_bool(finalize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stream_partial,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQwenAsrBridgeQwenAsrEngineStreamPushConstMeta,
        argValues: [that, samples, finalize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQwenAsrBridgeQwenAsrEngineStreamPushConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_stream_push",
        argNames: ["that", "samples", "finalize"],
      );

  @override
  Future<void> crateApiQwenAsrBridgeQwenAsrEngineStreamReset({
    required QwenAsrEngine that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQwenAsrBridgeQwenAsrEngineStreamResetConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQwenAsrBridgeQwenAsrEngineStreamResetConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_stream_reset",
        argNames: ["that"],
      );

  @override
  Future<String?> crateApiQwenAsrBridgeQwenAsrEngineTranscribeFile({
    required QwenAsrEngine that,
    required String wavPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          sse_encode_String(wavPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQwenAsrBridgeQwenAsrEngineTranscribeFileConstMeta,
        argValues: [that, wavPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiQwenAsrBridgeQwenAsrEngineTranscribeFileConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_transcribe_file",
        argNames: ["that", "wavPath"],
      );

  @override
  Future<String?> crateApiQwenAsrBridgeQwenAsrEngineTranscribePcm({
    required QwenAsrEngine that,
    required List<double> samples,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          sse_encode_list_prim_f_32_loose(samples, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQwenAsrBridgeQwenAsrEngineTranscribePcmConstMeta,
        argValues: [that, samples],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQwenAsrBridgeQwenAsrEngineTranscribePcmConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_transcribe_pcm",
        argNames: ["that", "samples"],
      );

  @override
  Future<String?> crateApiQwenAsrBridgeQwenAsrEngineTranscribeWavBuffer({
    required QwenAsrEngine that,
    required List<int> wavData,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(wavData, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiQwenAsrBridgeQwenAsrEngineTranscribeWavBufferConstMeta,
        argValues: [that, wavData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiQwenAsrBridgeQwenAsrEngineTranscribeWavBufferConstMeta =>
      const TaskConstMeta(
        debugName: "QwenAsrEngine_transcribe_wav_buffer",
        argNames: ["that", "wavData"],
      );

  @override
  Future<void> crateApiQwenAsrBridgeInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQwenAsrBridgeInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQwenAsrBridgeInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_QwenAsrEngine => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_QwenAsrEngine => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine;

  @protected
  QwenAsrEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QwenAsrEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  QwenAsrEngine
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QwenAsrEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  QwenAsrEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return QwenAsrEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  QwenAsrEngine
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
      raw,
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  QwenAsrEngine?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
            raw,
          );
  }

  @protected
  StreamPartial dco_decode_stream_partial(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StreamPartial(
      text: dco_decode_String(arr[0]),
      provisional: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  QwenAsrEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return QwenAsrEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  QwenAsrEngine
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return QwenAsrEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  QwenAsrEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return QwenAsrEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  QwenAsrEngine
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
      deserializer,
    ));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QwenAsrEngine?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  StreamPartial sse_decode_stream_partial(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_provisional = sse_decode_String(deserializer);
    return StreamPartial(text: var_text, provisional: var_provisional);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    QwenAsrEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as QwenAsrEngineImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    QwenAsrEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as QwenAsrEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    QwenAsrEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as QwenAsrEngineImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    QwenAsrEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
      self,
      serializer,
    );
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
    QwenAsrEngine? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQwenAsrEngine(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_stream_partial(StreamPartial self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.provisional, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class QwenAsrEngineImpl extends RustOpaque implements QwenAsrEngine {
  // Not to be used by end users
  QwenAsrEngineImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  QwenAsrEngineImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_QwenAsrEngine,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_QwenAsrEngine,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_QwenAsrEnginePtr,
  );

  /// Get last transcription performance stats as a formatted string.
  String perfStats() => RustLib.instance.api
      .crateApiQwenAsrBridgeQwenAsrEnginePerfStats(that: this);

  /// Set the forced language. Returns false if the language is invalid.
  ///
  /// A non-empty language turns multilingual auto-detection off. Pass an empty
  /// string to clear the forced language (returns to the default decode path).
  bool setLanguage({required String language}) =>
      RustLib.instance.api.crateApiQwenAsrBridgeQwenAsrEngineSetLanguage(
        that: this,
        language: language,
      );

  /// Enable/disable opt-in multilingual auto-detection for live streaming.
  ///
  /// When enabled, any forced language is cleared and the decoder re-detects
  /// language from fresh audio at every utterance boundary (silence → EOT),
  /// dropping the past-text carry so a previous utterance's language cannot
  /// drag the next into translation. Session-level: apply before
  /// [`QwenAsrEngine::stream_reset`]; no model reload required.
  void setMultilingual({required bool enabled}) =>
      RustLib.instance.api.crateApiQwenAsrBridgeQwenAsrEngineSetMultilingual(
        that: this,
        enabled: enabled,
      );

  /// Enable reusing previously decoded text as decoder context across chunks
  /// (prefix rollback). Recommended `true` for live streaming quality; matches
  /// the CLI `--stream` path.
  void setPastTextConditioning({required bool enabled}) => RustLib.instance.api
      .crateApiQwenAsrBridgeQwenAsrEngineSetPastTextConditioning(
        that: this,
        enabled: enabled,
      );

  /// Set the segment duration in seconds (0 = no segmentation).
  void setSegmentSec({required double sec}) => RustLib.instance.api
      .crateApiQwenAsrBridgeQwenAsrEngineSetSegmentSec(that: this, sec: sec);

  /// Configure the engine's internal streaming chunk size in seconds
  /// (default 8.0). Smaller values emit partial transcripts more frequently
  /// (lower latency) at some throughput cost. This is the primary live-latency
  /// tuning knob and is independent of the mic push-buffer size on the Dart
  /// side.
  void setStreamChunkSec({required double sec}) =>
      RustLib.instance.api.crateApiQwenAsrBridgeQwenAsrEngineSetStreamChunkSec(
        that: this,
        sec: sec,
      );

  /// Configure max new tokens decoded per chunk (default 32).
  void setStreamMaxNewTokens({required int tokens}) => RustLib.instance.api
      .crateApiQwenAsrBridgeQwenAsrEngineSetStreamMaxNewTokens(
        that: this,
        tokens: tokens,
      );

  /// Configure the streaming token rollback window (default 5). Larger values
  /// re-decode more of the tail each chunk for higher stability.
  void setStreamRollback({required int tokens}) =>
      RustLib.instance.api.crateApiQwenAsrBridgeQwenAsrEngineSetStreamRollback(
        that: this,
        tokens: tokens,
      );

  /// Configure how many leading chunks stay "unfixed" before tokens are
  /// progressively committed to the stable transcript.
  ///
  /// The engine default (99) effectively holds all output until `finalize`,
  /// which for a fast-pushed live stream truncates at `max_new_tokens`. Set a
  /// small value (e.g. 2) for correct progressive incremental streaming.
  void setStreamUnfixedChunks({required int chunks}) => RustLib.instance.api
      .crateApiQwenAsrBridgeQwenAsrEngineSetStreamUnfixedChunks(
        that: this,
        chunks: chunks,
      );

  /// Enable/disable opt-in discrete per-utterance segmentation ("VAD Live")
  /// for live streaming.
  ///
  /// When enabled, the frame-level silence-boundary VAD scan runs and each
  /// detected utterance boundary performs a hard segment reset: the committed
  /// text carry and the encoder window/cache are dropped so the next utterance
  /// decodes from a clean KV/encoder state (discrete segmentation) rather than
  /// a rolling continuation. Independent of [`QwenAsrEngine::set_multilingual`]
  /// — either can drive the scan and their reset actions compose. Session-level:
  /// apply before [`QwenAsrEngine::stream_reset`]; no model reload required.
  void setVadSegmentReset({required bool enabled}) =>
      RustLib.instance.api.crateApiQwenAsrBridgeQwenAsrEngineSetVadSegmentReset(
        that: this,
        enabled: enabled,
      );

  /// Push a new chunk of PCM audio into the live streaming session and return
  /// the current **stable** transcript plus the newest **provisional** tail.
  ///
  /// `samples`: new PCM chunk (f32, 16 kHz, mono, values in -1.0..1.0).
  /// `finalize`: set true on the final push (Stop) to flush remaining audio
  ///             and emit all rollback-buffered tokens.
  ///
  /// Returns a [`StreamPartial`]: `text` is the committed stable transcript
  /// (same as before), `provisional` is the unfixed tail (empty when none, and
  /// always empty after finalize). Runs on a flutter_rust_bridge worker thread,
  /// so the UI stays responsive while a push is in flight.
  Future<StreamPartial> streamPush({
    required List<double> samples,
    required bool finalize,
  }) => RustLib.instance.api.crateApiQwenAsrBridgeQwenAsrEngineStreamPush(
    that: this,
    samples: samples,
    finalize: finalize,
  );

  /// Reset the streaming session for a new utterance. Clears the accumulated
  /// audio buffer and token history but keeps the loaded tokenizer/model.
  ///
  /// Call once before starting a fresh live-capture session.
  Future<void> streamReset() => RustLib.instance.api
      .crateApiQwenAsrBridgeQwenAsrEngineStreamReset(that: this);

  /// Transcribe a WAV file at the given path.
  Future<String?> transcribeFile({required String wavPath}) =>
      RustLib.instance.api.crateApiQwenAsrBridgeQwenAsrEngineTranscribeFile(
        that: this,
        wavPath: wavPath,
      );

  /// Transcribe raw PCM f32 samples (16kHz mono).
  Future<String?> transcribePcm({required List<double> samples}) =>
      RustLib.instance.api.crateApiQwenAsrBridgeQwenAsrEngineTranscribePcm(
        that: this,
        samples: samples,
      );

  /// Transcribe from a WAV file buffer (bytes).
  Future<String?> transcribeWavBuffer({required List<int> wavData}) => RustLib
      .instance
      .api
      .crateApiQwenAsrBridgeQwenAsrEngineTranscribeWavBuffer(
        that: this,
        wavData: wavData,
      );
}
